# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefield',
            name='identifier',
            field=models.CharField(default='jj', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='identifier',
            field=models.CharField(default='jj', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datefield',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datefield',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
