# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170905_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefield',
            name='date',
        ),
    ]
