# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_datefield_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFieldAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.DateField')),
            ],
        ),
        migrations.CreateModel(
            name='TextFieldAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('text', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='text',
        ),
        migrations.AddField(
            model_name='textfieldanswers',
            name='extends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.TextField'),
        ),
    ]
