# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170905_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30, null=True)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='CheckFieldAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('check', models.NullBooleanField()),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.CheckField')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30, null=True)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceFieldAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('choice', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30, null=True)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.ChoiceField')),
            ],
        ),
        migrations.AlterField(
            model_name='textfieldanswers',
            name='extends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.TextField'),
        ),
        migrations.AddField(
            model_name='choicefieldanswers',
            name='extends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.ChoiceFieldOptions'),
        ),
    ]
