# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20170905_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicefieldoptions',
            name='check',
        ),
        migrations.AlterField(
            model_name='textfieldanswers',
            name='extends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.TextField'),
        ),
    ]
