# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20170913_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfieldanswers',
            name='extends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.TextField'),
        ),
    ]
